# Generated by Django 3.2.5 on 2021-07-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrooms',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
